name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
        
      - name: Install Ninja
        run: sudo apt-get -y install ninja-build

      - name: Build BunjiLearn
        run: bash ./scripts/compile.sh

      - name: Run Tests
        run: ninja -C build test
