name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Ninja
        run: sudo apt-get -y install ninja-build

      - name: Build BunjiLearn
        run: bash ./scripts/compile.sh
